// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvyRSTVXyw5iGbkjPffcB1uj3m3uliiFM',
    appId: '1:305880774570:web:39a3847f3ac7f2fd3f1dd3',
    messagingSenderId: '305880774570',
    projectId: 'gorotas-app',
    authDomain: 'gorotas-app.firebaseapp.com',
    storageBucket: 'gorotas-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6tzC4_hnYnl_ctviXKGOPHRrXM_40Tw',
    appId: '1:305880774570:android:da7e19c1351225e93f1dd3',
    messagingSenderId: '305880774570',
    projectId: 'gorotas-app',
    storageBucket: 'gorotas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZI3KAM_5p3yx3fNK1X4K_WxSTlocP_0',
    appId: '1:305880774570:ios:c6502a868b7697503f1dd3',
    messagingSenderId: '305880774570',
    projectId: 'gorotas-app',
    storageBucket: 'gorotas-app.firebasestorage.app',
    iosBundleId: 'com.example.descontino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVZI3KAM_5p3yx3fNK1X4K_WxSTlocP_0',
    appId: '1:305880774570:ios:c6502a868b7697503f1dd3',
    messagingSenderId: '305880774570',
    projectId: 'gorotas-app',
    storageBucket: 'gorotas-app.firebasestorage.app',
    iosBundleId: 'com.example.descontino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvyRSTVXyw5iGbkjPffcB1uj3m3uliiFM',
    appId: '1:305880774570:web:f8addb66a9c4cef83f1dd3',
    messagingSenderId: '305880774570',
    projectId: 'gorotas-app',
    authDomain: 'gorotas-app.firebaseapp.com',
    storageBucket: 'gorotas-app.firebasestorage.app',
  );
}
